version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # - setup_remote_docker

      # - run: git submodule update --init --recursive

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: ./gradlew dependencies

      - run: ./gradlew clean build
      #--rerun-tasks

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # - run: docker build -t $DOCKER_TAG .

      # - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # - run: docker push $DOCKER_TAG
